# Generated by Django 3.2.4 on 2021-07-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210718_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ststus',
            new_name='status',
        ),
    ]
